NumPy是Python语言的一个扩充程序库。支持高级大量的维度数组与矩阵运算，此外也针对数组运算提供大量的数学函数库。Numpy内部解除了Python的PIL(全局解释器锁),运算效率极好,是大量机器学习框架的基础库!

# 1 基础用法

## 1.1 将普通数组转换成Numpy数组

In [1]:
import numpy as np
axis_1 = np.array([1, 2, 3])#将数组转换成Numpy类型的一维数组
axis_2 = np.array([[1,3], [2, 3], [4, 1]])# 二维数组
axis_3 = np.array([[[1,3,4]], [[1,4,4]]]) # 三维数组

### 1.1.1 查看numpy数组属性

In [2]:
print(axis_1.size)
print(axis_1.shape)# 输出数组形状
print(axis_1.ndim)# 输出数组维度
print(axis_1.dtype)# 输出数组元素类型

3
(3,)
1
int32


## 1.2 快速创建Numpy数组

In [3]:
# 创建内容为1形状为3*3的数组
print(np.ones([3, 3]))
# 创建内容为0形状为3*3的数组
print(np.zeros([3,3]))
# 创建二维随机数组
print(np.random.rand(3, 3))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0.08333091 0.70982272 0.1129198 ]
 [0.17920537 0.28903072 0.08721166]
 [0.15045447 0.57635979 0.24099472]]


## 1.3 深拷贝与浅拷贝

In [4]:
# 浅拷贝
a = np.asarray(np.ones([2,3]))# 浅拷贝
b = np.array(np.ones([2,3]))# 深拷贝

# 2 numpy 计算

## 2.1 统计运算

### 2.1.1 将每个元素与设定值进行比较

In [5]:
score = np.array([[99, 88], [77, 90], [23, 87]])
print(score > 60)

[[ True  True]
 [ True  True]
 [False  True]]


### 2.1.2 修改数组中不符合要求的元素

In [6]:
# 将数组总分数低于60的替换成100
new_score = np.where(score<60, 100, score)
print(new_score)

[[ 99  88]
 [ 77  90]
 [100  87]]


### 2.1.3 获取行列(某一轴)的最大最小值

In [7]:
row_max = np.amax(score, axis=0)# 获取维度为0的最大值
row_min = np.amin(score, axis=1)# 获取维度为1的最小值
print(row_max, row_min)

[99 90] [88 77 23]


### 2.1.4 计算某一轴的平均值

In [8]:
row_mean = np.mean(score, axis=0)
print(row_mean)

[66.33333333 88.33333333]


### 2.1.5 计算某一轴的方差

In [9]:
row_std = np.std(score, axis=0)
print(row_std)

[31.93048004  1.24721913]


### 2.1.6 为某一轴做四则运算

In [11]:
score = np.array([[99, 88], [77, 90], [23, 87]])
score[:, 0] = score[:, 0]+5 # 取出数组的第一位+5 并重新赋值给同样的位置
print(score)

[[104  88]
 [ 82  90]
 [ 28  87]]
